; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
include_dir = ${PROJECT_DIR}/include
src_dir     = ${PROJECT_DIR}/src

[env]
platform      = atmelavr
board         = megaatmega2560
framework     = arduino
upload_port   = com5
build_flags   = -Wall -Wextra -std=gnu99 -DF_CPU=16000000UL
lib_extra_dirs = ${PROJECT_DIR}/lib

[env:Controller_atmega]
build_src_filter = +<controller_atmega/*.c> +<controller_atmega/modules/*.c>

[env:Robot_atmega]
build_src_filter = +<robot_atmega/*.c> +<robot_atmega/modules/*.c>