; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
include_dir = ${PROJECT_DIR}/include
src_dir = ${PROJECT_DIR}

[env]
platform = atmelavr
board = megaatmega2560
framework = arduino
upload_port = com17


[env:Controller]
build_src_filter =
  +<src/*.c>
  -<src/Robot.c>

[env:Robot]
build_src_filter =
  +<src/*.c>
  -<src/Controller.c>

; LABS
; lab 1
[env:lab1_1_1]
build_src_filter = +<labs/lab1/lab1_1_1.c>
;build_flags = -I src

[env:lab1_1_2]
build_src_filter = +<labs/lab1/lab1_1_2.c>

[env:lab1_1_3]
build_src_filter = +<labs/lab1/lab1_1_3.c>

[env:lab2_1]
build_src_filter = 
  +<labs/lab2/map.c>
  +<labs/lab2/lab2_1.c>

[env:lab2_2]
build_src_filter = 
  +<labs/lab2/map.c>
  +<labs/lab2/lab2_2.c>